### ISSUE TITLE
CodeQuality: use GitHub Actions to help with static analysis of the repo's codebase.

### ISSUE THREAD

**Issue by julianharty** [commercetest/nlnet#31]
### Context
In #29 we added pre-commit hooks, these run before the commit completes in our local development environment. As many of the projects we support are hosted on github.com and some will use GitHub Actions let's learn more about these by implementing them for this project.

TBD what sort of GitHub Actions would be useful for this codebase now, and as we add automated tests, etc.

**Comment by julianharty** [comment]
Let's add their coverage badge to the repo, assuming that's practical. https://github.com/marketplace/actions/coverage-badge

- https://github.com/dbrgn/coverage-badge
- https://github.com/marketplace/actions/coverage-py-badge
- https://smarie.github.io/python-genbadge/ 

Of these I've chosen genbadges initially as it looks most promising as a general purpose approach to generating badges.

**Comment by tnzmnjm** [comment]
Public repositories receive unlimited free minutes for running workflows on Linux, macOS, and Windows runners.
https://github.com/pricing
