### ISSUE TITLE
Add command-line argument support for input and output files

### ISSUE THREAD

**Issue by julianharty** [commercetest/nlnet#45]
### Context
We now have at least 3 scripts that read content from input files and write updated and additional content to output files. Currently these filenames are often hardcoded in the scripts, this makes the scripts less flexible for users who may wish to use different inputs, etc. 

Let's add command-line options, with the current filenames as default values, to the processing scripts in the `./src` folder. Let's also update the repo's README to document the new capabilities.

**Comment by tnzmnjm** [comment]
- changed the flags `parser.add_argument(
        "--input-file",
        type=str,
        default=str(Path("data/original_github_df.csv")),
        help="Path to the input CSV file."
    )


    parser.add_argument(
        "--output-file",
        type=str,
        default=str(Path("data/updated_local_github_df_test_count1.csv")),
        help="Path to the output CSV file."
    )`
- Amended the script to use these flags
- added these flags as parameters in my pycharm (`--input-file data/test/original_github_df.csv --output-file data/test/updated_local_github_df_test_count.csv`)
- script works as expected
- This change will be part of the PR #50

**Comment by tnzmnjm** [comment]
- I have added 2 flags for the script `src/github_repo_request_local.py`  : 
-- `--ttl-file`
 -- `--test-file-list`

- I have also added `argparse flags` to the script `utils/initial_data_preparation.py` . The flags are: 
-- `--input-file`
-- `--output-folder`
