### ISSUE TITLE
Improve the initial data preparation and reporting

### ISSUE THREAD

**Issue by julianharty** [commercetest/nlnet#53]
### Context
Currently we have three scripts connected by intermediate data files. Some processing is duplicated in the code that queries repos remotely on github.com and the code that clones repos locally before performing local analysis. 

We also don't provide much reporting of entries that lack data or that are no longer available at the specified URL.

Code such as:

- `filter_out_incomplete_urls(...)` seems better located in the data preparation than in the data processing. 
- `check_and_clean_data(...)` currently doesn't clean the data and it only provides a very brief summary of the issues it discovers.

**Comment by julianharty** [comment]
In terms of reporting; I'd like to experiment with both data-reporting and visual-reporting.

Data reporting would include RDF files, probably in turtle format, and formats that are easy to process further e.g. as Dataframes and/or in online services such as Big Query.

Visual reporting  could include graphs, plots, and especially Sankey diagrams: https://python-graph-gallery.com/sankey-diagram/ which may help to make data quality issues easy to spot; and also - for repos that are successfully queried - groupings of results such as the count of test files, tests, etc.

**Comment by tnzmnjm** [comment]
- added the functions `filter_out_incomplete_urls` , `get_base_repo_url` to the script `utils/initial_data_preparation.py`
- changed the imports in the script `tests/test_github_repo_request_local.py` accordingly - Import the functions `filter_out_incomplete_urls` and `get_base_repo_url`  
from their new location `utils.initial_data_preparation`- ran the tests --> all passed successfully
- ran the 3 scripts
