### ISSUE TITLE
Writing unit tests for some or all of the various helper functions in the script `utils/initial_data_preparation.py`

### ISSUE THREAD

**Issue by tnzmnjm** [commercetest/nlnet#72]

**Comment by julianharty** [comment]
As per comments in [#68](https://github.com/commercetest/nlnet/pull/68/files#r1601796858) pyhamcrest https://pyhamcrest.readthedocs.io/en/release-1.8/tutorial/ would be worth experimenting with.

**Comment by tnzmnjm** [comment]
Adding this based o the review from the PR #68: 
If the scripts accept http (by converting the protocol to https: how about adding a test to confirm and demonstrate this happens?

**Comment by tnzmnjm** [comment]
This is done . PR #77
